### ISSUE TITLE
Mouse keys are not working for mac 1.3.1 dz60rgb_v2

### ISSUE THREAD

**Issue by nanomosfet** [the-via/releases#172]
As the title says when i bind my mouse keys they do not move the mouse courser
```
version: 1.3.1
files:
  - url: via-1.3.1-mac.dmg
    sha512: 0NEUE6ewToE28Y8j+beyO0cWNf9ifM4qBLnKGpW24AhrMZpz4lxIaQVqvp6enQnQuj3isCpiGWKVtsBh0uGItA==
    size: 100246493
path: via-1.3.1-mac.dmg
sha512: 0NEUE6ewToE28Y8j+beyO0cWNf9ifM4qBLnKGpW24AhrMZpz4lxIaQVqvp6enQnQuj3isCpiGWKVtsBh0uGItA==
releaseDate: '2020-06-19T03:11:06.304Z'
```
